modLoader="javafml"
loaderVersion="[40,)"
license="All-Rights-Reserved"

[[mods]]
modId="dg_lab"
version="1.1.3-forge-1.18.2"
displayName="DG_LAB"
authors="kbpf Xiao_Wu Pisces_Moze"
description="与DG_LAB设备链接"

# Forge dependency
[[dependencies.dg_lab]]
modId="forge"
mandatory=true
versionRange="[40,)"
ordering="NONE"
side="CLIENT"

# Minecraft dependency
[[dependencies.dg_lab]]
modId="minecraft"
mandatory=true
versionRange="[1.18.2,1.19)"
ordering="NONE"
side="CLIENT"

# Java版本检查已移除，因为Forge无法正确识别已安装的Java 17
# Java版本将通过其他方式检查
